### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by MohamedHNoor** [MohamedHNoor/recipe-app#9]
# Hi Code Reviewer 👋 👋 

## We are a group of two:

- [x] @MohamedHNoor 
- [x] @shegy28 
- [x] This is the [link](https://github.com/MohamedHNoor/recipe-app/projects/1) to our Kanban cards

**Comment by arslanbisharat** [comment]
Hi @MohamedHNoor,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
